info:
  build:
    version: ${version}

spring:
  application:
    name: LypsisCustomerService

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true