info:
  build:
    version: ${version}

spring:
  application:
    name: LypsisGatewayService

server:
  port: 8080

zuul:
  routes:
    user:
      path: /user/**
      url: http://localhost:8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
